import type { Coupon } from "@/lib/types";

/**
 * Проверенные партнерские предложения и промокоды из CPA-сети Saleads.pro с официальной маркировкой (ОРД / erid)
 */
export const CUSTOM_COUPONS: Coupon[] = [
  {
    id: 50005,
    promocode: {
      id: 50005,
      code: "SALEADS2026",
      bonusName: "Скидка 500 ₽ на оформление международной карты",
      terms: "Действует на выпуск виртуальной карты для оплаты зарубежных сервисов (ChatGPT, Steam, Spotify) и бронирования отелей.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5005,
      name: "Плати по миру",
      slug: "plati-po-miru",
      logo: "https://www.google.com/s2/favicons?domain=platipomiru.com&sz=128",
      category: "Сервисы и подписки",
      categorySlug: "servisy-i-podpiski",
      about: "Плати по миру — выпуск международных виртуальных карт для оплаты ChatGPT, Steam, Spotify, PlayStation и зарубежных покупок.",
      conditions: "Скидка применяется при переходе по партнерской ссылке и вводе промокода.",
      site: "https://platipomiru.com",
      activeBloggers: 3400,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/dz5lk?erid=2Vtzqwxtkav",
      landingLink: "https://my.saleads.pro/s/dz5lk?erid=2Vtzqwxtkav",
      ordMarker: "2Vtzqwxtkav",
      ordText: "Реклама. erid: 2Vtzqwxtkav",
    },
    extraLinks: [],
  },
  {
    id: 50008,
    promocode: {
      id: 50008,
      code: "saleads",
      bonusName: "Скидка 1 000 ₽ на первый заказ от 3 000 ₽ в IRNBY",
      terms: "Применяется при первом заказе от 3 000 ₽ на дизайнерскую спортивную и повседневную одежду брендов.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5008,
      name: "IRNBY",
      slug: "irnby",
      logo: "https://www.google.com/s2/favicons?domain=irnby.com&sz=128",
      category: "Одежда и обувь",
      categorySlug: "odezhda-i-obuv",
      about: "IRNBY (IronByIron) — дизайнерский российский бренд спортивной, повседневной одежды и аксессуаров.",
      conditions: "Скидка применяется в корзине при вводе промокода.",
      site: "https://irnby.com",
      activeBloggers: 4100,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/wxcod?erid=2VtzqxMLcBU",
      landingLink: "https://my.saleads.pro/s/wxcod?erid=2VtzqxMLcBU",
      ordMarker: "2VtzqxMLcBU",
      ordText: "Реклама. erid: 2VtzqxMLcBU",
    },
    extraLinks: [],
  },
  {
    id: 50020,
    promocode: {
      id: 50020,
      code: "", // Акция по ссылке
      bonusName: "1 000 ₽ бонус + вечное бесплатное обслуживание",
      terms: "Оформите бесплатную дебетовую карту Т-Банк Black. Получите 1 000 ₽ кэшбэка при первой покупке от 500 ₽, кэшбэк до 30% у партнеров и бесплатные переводы без комиссий.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5020,
      name: "Т-Банк",
      slug: "t-bank",
      logo: "https://www.google.com/s2/favicons?domain=tbank.ru&sz=128",
      category: "Финансы и кэшбэк",
      categorySlug: "finansy-i-keshbek",
      about: "Т-Банк (Тинькофф) — ведущий онлайн-банк с лучшим мобильным приложением, выгодным кэшбэком рублями и бесплатной доставкой карты представителем за 1 день.",
      conditions: "Промокод не требуется. Бонус и бесплатное обслуживание активируются автоматически при переходе и оформлении онлайн.",
      site: "https://my.saleads.pro/s/1f4rx?erid=2Vtzquih2e9",
      activeBloggers: 12500,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/1f4rx?erid=2Vtzquih2e9",
      landingLink: "https://my.saleads.pro/s/1f4rx?erid=2Vtzquih2e9",
      ordMarker: "2Vtzquih2e9",
      ordText: "Реклама. АО «ТБанк» erid: 2Vtzquih2e9",
    },
    extraLinks: [],
  },
];
