import type { Coupon } from "@/lib/types";

/**
 * Проверенные эксклюзивные промокоды для покупок и сервисов
 */
export const CUSTOM_COUPONS: Coupon[] = [
  {
    id: 50005,
    promocode: {
      id: 50005,
      code: "SALEADS2026",
      bonusName: "Скидка 500 ₽ на оформление международной карты",
      terms: "Действует на выпуск виртуальной карты для оплаты зарубежных сервисов (ChatGPT, Steam, Spotify) и бронирования отелей.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5005,
      name: "Плати по миру",
      slug: "plati-po-miru",
      logo: "https://www.google.com/s2/favicons?domain=platipomiru.com&sz=128",
      category: "Сервисы и подписки",
      categorySlug: "servisy-i-podpiski",
      about: "Плати по миру — выпуск международных виртуальных карт для оплаты зарубежных сервисов и покупок.",
      conditions: "Скидка применяется при переходе по ссылке и вводе промокода.",
      site: "https://platipomiru.com",
      activeBloggers: 3400,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/dz5lk?erid=2Vtzqwxtkav",
      landingLink: "https://my.saleads.pro/s/dz5lk?erid=2Vtzqwxtkav",
      ordMarker: "2Vtzqwxtkav",
      ordText: "Реклама. erid: 2Vtzqwxtkav",
    },
    extraLinks: [],
  },
  {
    id: 50008,
    promocode: {
      id: 50008,
      code: "saleads",
      bonusName: "Скидка 1 000 ₽ на первый заказ от 3 000 ₽ в IRNBY",
      terms: "Применяется при первом заказе от 3 000 ₽ на дизайнерскую спортивную и повседневную одежду брендов.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5008,
      name: "IRNBY",
      slug: "irnby",
      logo: "https://www.google.com/s2/favicons?domain=irnby.com&sz=128",
      category: "Одежда и обувь",
      categorySlug: "odezhda-i-obuv",
      about: "IRNBY (IronByIron) — дизайнерский российский бренд спортивной, повседневной одежды и аксессуаров.",
      conditions: "Скидка применяется в корзине при вводе промокода.",
      site: "https://irnby.com",
      activeBloggers: 4100,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/wxcod?erid=2VtzqxMLcBU",
      landingLink: "https://my.saleads.pro/s/wxcod?erid=2VtzqxMLcBU",
      ordMarker: "2VtzqxMLcBU",
      ordText: "Реклама. erid: 2VtzqxMLcBU",
    },
    extraLinks: [],
  },
  {
    id: 50030,
    promocode: {
      id: 50030,
      code: "", // Скидка по ссылке
      bonusName: "СберПрайм 60 дней за 1 ₽ + 5% кэшбэк на игры в GamersHub",
      terms: "Получайте 5% бонусами Спасибо с каждой покупки игр, ключей и пополнения кошелька на GamersHub без комиссий. Для новичков действует пробный период СберПрайм 60 дней за 1 ₽ или годовая подписка за 333 ₽/мес.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: "/images/sberprime.png",
      group: "perfluence",
    },
    store: {
      id: 5030,
      name: "СберПрайм",
      slug: "sberprime",
      logo: "https://www.google.com/s2/favicons?domain=sberbank.ru&sz=128",
      category: "Сервисы и подписки",
      categorySlug: "servisy-i-podpiski",
      about: "СберПрайм — единая подписка на сервисы: фильмы в Okko, музыка в Звуке, бесплатная доставка и повышенный кэшбэк бонусами Спасибо на покупки и игры на GamersHub.",
      conditions: "Промокод не требуется. Перейдите по ссылке и оформите подписку. Открывать через российские браузеры.",
      site: "https://sberbank1.prfl.me/sites/ynqvsf?erid=2RanymUAmpP",
      activeBloggers: 15400,
    },
    affiliate: {
      link: "https://sberbank1.prfl.me/sites/ynqvsf?erid=2RanymUAmpP",
      landingLink: "https://sberbank1.prfl.me/sites/ynqvsf?erid=2RanymUAmpP",
      ordMarker: "2RanymUAmpP",
      ordText: "Реклама. Рекламодатель — АО «ЦПЛ» (ОГРН: 1117746689840, г. Москва). erid: 2RanymUAmpP",
    },
    extraLinks: [],
  },
  {
    id: 50040,
    promocode: {
      id: 50040,
      code: "E-FIX-AU1A2MZ",
      bonusName: "Скидка 300 ₽ на заказ",
      terms: "Минус 300 ₽ при оформлении одного любого заказа от 1500 ₽. Промокод действует не на все товары и заказы.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "perfluence",
    },
    store: {
      id: 5040,
      name: "Fix Price",
      slug: "fix-price",
      logo: "https://www.google.com/s2/favicons?domain=fix-price.com&sz=128",
      category: "Все для дома",
      categorySlug: "vse-dlya-doma",
      about: "Fix Price — сеть магазинов фиксированных низких цен: снеки, сладости, товары для дома и быта.",
      conditions: "Промокод применяется при заказе от 1500 ₽. Действует не на все товары и заказы, условия акции на сайте fix-price.com.",
      site: "https://fix-price.com",
      activeBloggers: 0,
    },
    affiliate: {
      link: "https://fixprice.prfl.me/smart_zakupka/ba14ds?erid=2RanymFMnjm",
      landingLink: "https://fixprice.prfl.me/smart_zakupka/ba14ds?erid=2RanymFMnjm",
      ordMarker: "2RanymFMnjm",
      ordText: "Реклама. ООО «Бэст Прайс», ОГРН 1075047007496, 141401, Московская обл., г. Химки, ул. Победы, д. 11.",
    },
    extraLinks: [],
  },
  {
    id: 50045,
    promocode: {
      id: 50045,
      code: "6ZJP6PZFQH",
      bonusName: "Скидка до 50% на Кинопоиск + 60 дней подписки",
      terms: "Промокод даёт скидку до 50% на подписку Кинопоиск (Яндекс Плюс). Действует на первый заказ, до 30.09.2026. Условия акции на сайте Кинопоиска.",
      expires: "2026-09-30",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "perfluence",
    },
    store: {
      id: 5045,
      name: "Кинопоиск",
      slug: "kinopoisk",
      logo: "https://www.google.com/s2/favicons?domain=kinopoisk.ru&sz=128",
      category: "Онлайн-кинотеатры",
      categorySlug: "onlayn-kinoteatry",
      about: "Кинопоиск — онлайн-кинотеатр от Яндекса: фильмы, сериалы, мультфильмы по подписке Яндекс Плюс.",
      conditions: "Промокод применяется при оформлении подписки Яндекс Плюс с Кинопоиском. Действует до 30.09.2026 23:59.",
      site: "https://www.kinopoisk.ru",
      activeBloggers: 10000,
    },
    affiliate: {
      link: "https://kp45.prfl.me/sites/b42qv0?erid=2Ranyk7g9Y7",
      landingLink: "https://kp45.prfl.me/sites/b42qv0?erid=2Ranyk7g9Y7",
      ordMarker: "2Ranyk7g9Y7",
      ordText: "Реклама. ООО «ЯНДЕКС», ИНН 7736207543",
    },
    extraLinks: [],
  },
];
