import type { Coupon } from "@/lib/types";

/**
 * Статичные и ручные проверенные промокоды (Яндекс, Плати по миру, VK Места, IRNBY, Литрес, Технопарк, Librederm, ВсеИнструменты, Justfood, Нетология, Skillfactory, и др.)
 */
export const CUSTOM_COUPONS: Coupon[] = [
  {
    id: 50001,
    promocode: {
      id: 50001,
      code: "MARKET500",
      bonusName: "Скидка 500 ₽ на первый заказ от 2 500 ₽",
      terms: "Действует на первый заказ в приложении и на сайте Яндекс Маркет при сумме корзины от 2 500 ₽.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "yandex",
    },
    store: {
      id: 5001,
      name: "Яндекс Маркет",
      slug: "yandex-market",
      logo: "https://www.google.com/s2/favicons?domain=market.yandex.ru&sz=128",
      category: "Маркетплейсы",
      categorySlug: "marketplejsy",
      about: "Яндекс Маркет — огромный выбор товаров с быстрой доставкой: электроника, товары для дома, одежда и продукты.",
      conditions: "Скидка активируется в корзине при вводе промокода.",
      site: "https://market.yandex.ru",
      activeBloggers: 12000,
    },
    affiliate: {
      link: "https://market.yandex.ru",
      landingLink: "https://market.yandex.ru",
      ordMarker: "",
      ordText: "Реклама. ООО «Яндекс»",
    },
    extraLinks: [],
  },
  {
    id: 50002,
    promocode: {
      id: 50002,
      code: "PLUS30",
      bonusName: "30 дней бесплатной подписки Яндекс Плюс",
      terms: "Бесплатный доступ к Кинопоиску, Яндекс Музыке и кэшбэку баллами Плюса для новых пользователей.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "yandex",
    },
    store: {
      id: 5002,
      name: "Яндекс Плюс",
      slug: "yandex-plus",
      logo: "https://www.google.com/s2/favicons?domain=plus.yandex.ru&sz=128",
      category: "Сервисы и подписки",
      categorySlug: "servisy-i-podpiski",
      about: "Единая подписка на сервисы Яндекса: фильмы на Кинопоиске, треки на Яндекс Музыке и кэшбэк баллами.",
      conditions: "Только для пользователей без активной подписки.",
      site: "https://plus.yandex.ru",
      activeBloggers: 9500,
    },
    affiliate: {
      link: "https://plus.yandex.ru",
      landingLink: "https://plus.yandex.ru",
      ordMarker: "",
      ordText: "Реклама. ООО «Яндекс»",
    },
    extraLinks: [],
  },
  {
    id: 50003,
    promocode: {
      id: 50003,
      code: "EDA20",
      bonusName: "Скидка 20% на первый заказ из ресторанов",
      terms: "Действует на первый заказ в Яндекс Еде от 1 000 ₽ в ресторанах-партнерах.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "yandex",
    },
    store: {
      id: 5003,
      name: "Яндекс Еда",
      slug: "yandex-eda",
      logo: "https://www.google.com/s2/favicons?domain=eda.yandex.ru&sz=128",
      category: "Доставка еды",
      categorySlug: "dostavka-edy",
      about: "Быстрая доставка готовой еды из любимых кафе и ресторанов вашего города от 30 минут.",
      conditions: "Скидка действует при заказе через приложение или сайт.",
      site: "https://eda.yandex.ru",
      activeBloggers: 14000,
    },
    affiliate: {
      link: "https://eda.yandex.ru",
      landingLink: "https://eda.yandex.ru",
      ordMarker: "",
      ordText: "Реклама. ООО «Яндекс.Еда»",
    },
    extraLinks: [],
  },
  {
    id: 50004,
    promocode: {
      id: 50004,
      code: "TRAVEL15",
      bonusName: "Скидка до 15% на бронирование отелей по России",
      terms: "Действует на первое бронирование отелей и гостиниц на Яндекс Путешествиях.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "yandex",
    },
    store: {
      id: 5004,
      name: "Яндекс Путешествия",
      slug: "yandex-travel",
      logo: "https://www.google.com/s2/favicons?domain=travel.yandex.ru&sz=128",
      category: "Путешествия и туризм",
      categorySlug: "puteshestviya-i-turizm",
      about: "Поиск и бронирование отелей, авиабилетов, ж/д билетов и туров с кэшбэком до 20% баллами Плюса.",
      conditions: "Скидка применяется при онлайн-оплате бронирования.",
      site: "https://travel.yandex.ru",
      activeBloggers: 8200,
    },
    affiliate: {
      link: "https://travel.yandex.ru",
      landingLink: "https://travel.yandex.ru",
      ordMarker: "",
      ordText: "Реклама. ООО «Яндекс Вертикали»",
    },
    extraLinks: [],
  },
  {
    id: 50005,
    promocode: {
      id: 50005,
      code: "SALEADS2026",
      bonusName: "Скидка 500 ₽ на оформление виртуальной карты",
      terms: "Действует на выпуск международной карты для оплаты зарубежных сервисов, игр и подписок.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5005,
      name: "Плати по миру",
      slug: "plati-po-miru",
      logo: "https://www.google.com/s2/favicons?domain=platipomiru.com&sz=128",
      category: "Сервисы и подписки",
      categorySlug: "servisy-i-podpiski",
      about: "Плати по миру — выпуск международных виртуальных карт для оплаты ChatGPT, Steam, Spotify, PlayStation и отелей за рубежом.",
      conditions: "Скидка применяется при переходе по ссылке и вводе промокода.",
      site: "https://platipomiru.com",
      activeBloggers: 3400,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/dz5lk?erid=2Vtzqwxtkav",
      landingLink: "https://my.saleads.pro/s/dz5lk?erid=2Vtzqwxtkav",
      ordMarker: "2Vtzqwxtkav",
      ordText: "Реклама. erid: 2Vtzqwxtkav",
    },
    extraLinks: [],
  },
  {
    id: 50006,
    promocode: {
      id: 50006,
      code: "SALEADSPREM2026",
      bonusName: "Скидка 1 000 ₽ на тариф Premium",
      terms: "Скидка на премиальную карту с повышенным лимитом и приоритетной поддержкой 24/7.",
      expires: "2026-12-31",
      isHit: false,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5005,
      name: "Плати по миру",
      slug: "plati-po-miru",
      logo: "https://www.google.com/s2/favicons?domain=platipomiru.com&sz=128",
      category: "Сервисы и подписки",
      categorySlug: "servisy-i-podpiski",
      about: "Плати по миру — сервис выпуска международных виртуальных карт для граждан РФ.",
      conditions: "Скидка применяется по реферальной ссылке и вводу промокода.",
      site: "https://platipomiru.com",
      activeBloggers: 3400,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/dz5lk?erid=2Vtzqwxtkav",
      landingLink: "https://my.saleads.pro/s/dz5lk?erid=2Vtzqwxtkav",
      ordMarker: "2Vtzqwxtkav",
      ordText: "Реклама. erid: 2Vtzqwxtkav",
    },
    extraLinks: [],
  },
  {
    id: 50007,
    promocode: {
      id: 50007,
      code: "VKMESTA",
      bonusName: "Скидки и спецпредложения на авторские экскурсии по РФ",
      terms: "Бронирование авторских туров по всей России от аттестованных гидов с бесплатной отменой.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5007,
      name: "VK Места",
      slug: "vk-mesta",
      logo: "https://www.google.com/s2/favicons?domain=vkmesta.ru&sz=128",
      category: "Путешествия и туризм",
      categorySlug: "puteshestviya-i-turizm",
      about: "VK Места — сервис бронирования авторских экскурсий и уникальных маршрутов по всей России от VK и гидов.",
      conditions: "Скидки и спецпредложения применяются при переходе по ссылке.",
      site: "https://vkmesta.ru",
      activeBloggers: 5200,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/7e6py?erid=2VtzqwtSSee",
      landingLink: "https://my.saleads.pro/s/7e6py?erid=2VtzqwtSSee",
      ordMarker: "2VtzqwtSSee",
      ordText: "Реклама. erid: 2VtzqwtSSee",
    },
    extraLinks: [],
  },
  {
    id: 50008,
    promocode: {
      id: 50008,
      code: "saleads",
      bonusName: "Скидка 1 000 ₽ для новых клиентов от 3 000 ₽ в IRNBY",
      terms: "Применяется при первом заказе от 3 000 ₽ на дизайнерскую спортивную одежду.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5008,
      name: "IRNBY",
      slug: "irnby",
      logo: "https://www.google.com/s2/favicons?domain=irnby.com&sz=128",
      category: "Одежда и обувь",
      categorySlug: "odezhda-i-obuv",
      about: "IRNBY (IronByIron) — дизайнерский российский бренд спортивной, повседневной одежды и аксессуаров.",
      conditions: "Скидка применяется в корзине при вводе промокода.",
      site: "https://irnby.com",
      activeBloggers: 4100,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/wxcod?erid=2VtzqxMLcBU",
      landingLink: "https://my.saleads.pro/s/wxcod?erid=2VtzqxMLcBU",
      ordMarker: "2VtzqxMLcBU",
      ordText: "Реклама. erid: 2VtzqxMLcBU",
    },
    extraLinks: [],
  },
  {
    id: 50010,
    promocode: {
      id: 50010,
      code: "LITRES",
      bonusName: "Скидка 25% на книги + книга в подарок в Литрес",
      terms: "Действует на весь каталог электронных и аудиокниг в приложении и на сайте Литрес.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5010,
      name: "Литрес",
      slug: "litres",
      logo: "https://www.google.com/s2/favicons?domain=litres.ru&sz=128",
      category: "Книги и образование",
      categorySlug: "knigi-i-obrazovanie",
      about: "Литрес — крупнейший сервис электронных и аудиокниг в России. Более 1 000 000 бестселлеров и новинок.",
      conditions: "Скидки и спецпредложения применяются при переходе по ссылке.",
      site: "https://my.saleads.pro/s/l0J1s?erid=2Vtzqwo5gzz",
      activeBloggers: 14000,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/l0J1s?erid=2Vtzqwo5gzz",
      landingLink: "https://my.saleads.pro/s/l0J1s?erid=2Vtzqwo5gzz",
      ordMarker: "2Vtzqwo5gzz",
      ordText: "Реклама. erid: 2Vtzqwo5gzz",
    },
    extraLinks: [],
  },
  {
    id: 50011,
    promocode: {
      id: 50011,
      code: "TECHNOPARK",
      bonusName: "Скидки и кэшбэк до 20% на технику в Технопарк",
      terms: "Действует на покупку бытовой техники, смартфонов и гаджетов ведущих мировых брендов.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5011,
      name: "Технопарк",
      slug: "tehnopark",
      logo: "https://www.google.com/s2/favicons?domain=technopark.ru&sz=128",
      category: "Электроника и техника",
      categorySlug: "elektronika-i-tehnika",
      about: "Технопарк — сеть премиальной бытовой техники и электроники с официальной гарантией и высоким сервисом.",
      conditions: "Скидки действуют онлайн при переходе по ссылке.",
      site: "https://my.saleads.pro/s/3mbtf?erid=2VtzqwMjwfU",
      activeBloggers: 8900,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/3mbtf?erid=2VtzqwMjwfU",
      landingLink: "https://my.saleads.pro/s/3mbtf?erid=2VtzqwMjwfU",
      ordMarker: "2VtzqwMjwfU",
      ordText: "Реклама. erid: 2VtzqwMjwfU",
    },
    extraLinks: [],
  },
  {
    id: 50012,
    promocode: {
      id: 50012,
      code: "LIBREDERM",
      bonusName: "Скидка до 30% и подарки к заказу косметики Librederm",
      terms: "Действует на весь ассортимент аптечной косметики Librederm в официальном магазине.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5012,
      name: "Librederm",
      slug: "librederm",
      logo: "https://www.google.com/s2/favicons?domain=librederm.ru&sz=128",
      category: "Красота и косметика",
      categorySlug: "krasota-i-kosmetika",
      about: "Librederm — международный бренд дерматологической и лечебной косметики для здоровья кожи.",
      conditions: "Акции и подарки активируются автоматически при переходе.",
      site: "https://my.saleads.pro/s/s92xr?erid=2VtzqxjkxeA",
      activeBloggers: 6200,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/s92xr?erid=2VtzqxjkxeA",
      landingLink: "https://my.saleads.pro/s/s92xr?erid=2VtzqxjkxeA",
      ordMarker: "2VtzqxjkxeA",
      ordText: "Реклама. erid: 2VtzqxjkxeA",
    },
    extraLinks: [],
  },
  {
    id: 50013,
    promocode: {
      id: 50013,
      code: "VSEINSTRUMENTI",
      bonusName: "Скидки до 40% на инструмент и ремонт в ВсеИнструменты.ру",
      terms: "Действует на строительный инструмент, садовую технику, автотовары и оснастку.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5013,
      name: "ВсеИнструменты.ру",
      slug: "vseinstrumenti-ru",
      logo: "https://www.google.com/s2/favicons?domain=vseinstrumenti.ru&sz=128",
      category: "Электроника и техника",
      categorySlug: "elektronika-i-tehnika",
      about: "ВсеИнструменты.ру — крупнейший онлайн-гипермаркет инструмента, оборудования и товаров для ремонта.",
      conditions: "Специальные цены действуют при заказе по партнерской ссылке.",
      site: "https://my.saleads.pro/s/pu9g3?erid=2VtzqwtTsNM",
      activeBloggers: 11000,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/pu9g3?erid=2VtzqwtTsNM",
      landingLink: "https://my.saleads.pro/s/pu9g3?erid=2VtzqwtTsNM",
      ordMarker: "2VtzqwtTsNM",
      ordText: "Реклама. erid: 2VtzqwtTsNM",
    },
    extraLinks: [],
  },
  {
    id: 50014,
    promocode: {
      id: 50014,
      code: "JUSTFOOD",
      bonusName: "Скидка до 20% на готовые рационы питания Justfood",
      terms: "Действует на заказ готового здорового питания с расчетом калорий на неделю для новых клиентов.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5014,
      name: "Justfood",
      slug: "justfood",
      logo: "https://www.google.com/s2/favicons?domain=justfood.pro&sz=128",
      category: "Доставка еды",
      categorySlug: "dostavka-edy",
      about: "Justfood — доставка готового здорового питания с расчетом БЖУ от шеф-поваров и диетологов.",
      conditions: "Скидка применяется при оформлении заказа на сайте.",
      site: "https://my.saleads.pro/s/okmjl?erid=2Vtzqxdzvbp",
      activeBloggers: 4800,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/okmjl?erid=2Vtzqxdzvbp",
      landingLink: "https://my.saleads.pro/s/okmjl?erid=2Vtzqxdzvbp",
      ordMarker: "2Vtzqxdzvbp",
      ordText: "Реклама. erid: 2Vtzqxdzvbp",
    },
    extraLinks: [],
  },
  {
    id: 50015,
    promocode: {
      id: 50015,
      code: "NETOLOGIYA",
      bonusName: "Скидка до 45% на обучение востребованным профессиям в Нетологии",
      terms: "Действует на курсы по программированию, маркетингу, аналитике, дизайну и бизнесу.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5015,
      name: "Нетология",
      slug: "netologiya",
      logo: "https://www.google.com/s2/favicons?domain=netology.ru&sz=128",
      category: "Книги и образование",
      categorySlug: "knigi-i-obrazovanie",
      about: "Нетология — одна из ведущих образовательных платформ в России. Помощь в трудоустройстве и диплом.",
      conditions: "Скидка применяется автоматически при переходе по ссылке.",
      site: "https://my.saleads.pro/s/y3kro?erid=2VtzquhBq3L",
      activeBloggers: 7500,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/y3kro?erid=2VtzquhBq3L",
      landingLink: "https://my.saleads.pro/s/y3kro?erid=2VtzquhBq3L",
      ordMarker: "2VtzquhBq3L",
      ordText: "Реклама. erid: 2VtzquhBq3L",
    },
    extraLinks: [],
  },
  {
    id: 50016,
    promocode: {
      id: 50016,
      code: "SKILLFACTORY",
      bonusName: "Скидка до 50% на IT-профессии в онлайн-школе Skillfactory",
      terms: "Действует на курсы Data Science, Python-разработки, тестирования и аналитики данных.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5016,
      name: "Skillfactory",
      slug: "skillfactory",
      logo: "https://www.google.com/s2/favicons?domain=skillfactory.ru&sz=128",
      category: "Книги и образование",
      categorySlug: "knigi-i-obrazovanie",
      about: "Skillfactory — ведущая онлайн-школа IT-профессий с упором на реальную практику и проекты в портфолио.",
      conditions: "Спецпредложение действует онлайн при переходе по ссылке.",
      site: "https://my.saleads.pro/s/Jo342?erid=2VtzqwERgYG",
      activeBloggers: 6800,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/Jo342?erid=2VtzqwERgYG",
      landingLink: "https://my.saleads.pro/s/Jo342?erid=2VtzqwERgYG",
      ordMarker: "2VtzqwERgYG",
      ordText: "Реклама. erid: 2VtzqwERgYG",
    },
    extraLinks: [],
  },
  {
    id: 50017,
    promocode: {
      id: 50017,
      code: "CONTENTED",
      bonusName: "Скидка до 45% на курсы графического, веб и 3D-дизайна в Contented",
      terms: "Действует на все направления школы дизайна: UX/UI, интерьеры, моушн и анимация.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5017,
      name: "Contented",
      slug: "contented",
      logo: "https://www.google.com/s2/favicons?domain=contented.ru&sz=128",
      category: "Книги и образование",
      categorySlug: "knigi-i-obrazovanie",
      about: "Contented — профильная школа дизайна в России. Обучение с нуля до уверенного трудоустройства.",
      conditions: "Скидки и акции активируются при переходе по ссылке.",
      site: "https://my.saleads.pro/s/9ilnb?erid=2VtzqweDBM2",
      activeBloggers: 5400,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/9ilnb?erid=2VtzqweDBM2",
      landingLink: "https://my.saleads.pro/s/9ilnb?erid=2VtzqweDBM2",
      ordMarker: "2VtzqweDBM2",
      ordText: "Реклама. erid: 2VtzqweDBM2",
    },
    extraLinks: [],
  },
  {
    id: 50018,
    promocode: {
      id: 50018,
      code: "TUTORONLINE",
      bonusName: "2 бесплатных вводных урока с репетитором в TutorOnline",
      terms: "Действует на индивидуальные занятия по школьным предметам и подготовке к ЕГЭ/ОГЭ.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5018,
      name: "TutorOnline",
      slug: "tutoronline",
      logo: "https://www.google.com/s2/favicons?domain=tutoronline.ru&sz=128",
      category: "Книги и образование",
      categorySlug: "knigi-i-obrazovanie",
      about: "TutorOnline — онлайн-школа с персональными репетиторами по всем предметам и иностранным языкам.",
      conditions: "Бесплатные уроки начисляются при регистрации по ссылке.",
      site: "https://my.saleads.pro/s/oivf4?erid=2Vtzqwz569p",
      activeBloggers: 3900,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/oivf4?erid=2Vtzqwz569p",
      landingLink: "https://my.saleads.pro/s/oivf4?erid=2Vtzqwz569p",
      ordMarker: "2Vtzqwz569p",
      ordText: "Реклама. erid: 2Vtzqwz569p",
    },
    extraLinks: [],
  },
  {
    id: 50019,
    promocode: {
      id: 50019,
      code: "MORETUT",
      bonusName: "Скидки до 30% на отдых и санатории на море в сервисе МореТут",
      terms: "Действует на бронирование отелей, пансионатов и санаториев на Черноморском побережье.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5019,
      name: "МореТут",
      slug: "moretut",
      logo: "https://www.google.com/s2/favicons?domain=moretut.ru&sz=128",
      category: "Путешествия и туризм",
      categorySlug: "puteshestviya-i-turizm",
      about: "МореТут — проверенный сервис бронирования отелей, санаториев и баз отдыха в Сочи, Крыму и Анапе.",
      conditions: "Скидки действуют онлайн при бронировании по ссылке.",
      site: "https://my.saleads.pro/s/9n7z8?erid=2Vtzqw9r2k8",
      activeBloggers: 3100,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/9n7z8?erid=2Vtzqw9r2k8",
      landingLink: "https://my.saleads.pro/s/9n7z8?erid=2Vtzqw9r2k8",
      ordMarker: "2Vtzqw9r2k8",
      ordText: "Реклама. erid: 2Vtzqw9r2k8",
    },
    extraLinks: [],
  },
  {
    id: 50026,
    promocode: {
      id: 50026,
      code: "OTPBANK",
      bonusName: "Бесплатное обслуживание и кэшбэк до 5% по ОТП Карте",
      terms: "Дебетовая карта с повышенным кэшбэком на супермаркеты, рестораны и бесплатными переводами.",
      expires: "2026-12-31",
      isHit: true,
      isUniversal: true,
      isFirstOrderOnly: false,
      region: "RU",
      isBarcode: false,
      barcodeImage: null,
      group: "saleads",
    },
    store: {
      id: 5026,
      name: "ОТП Банк",
      slug: "otp-bank",
      logo: "https://www.google.com/s2/favicons?domain=otpbank.ru&sz=128",
      category: "Финансы и банки",
      categorySlug: "finansy-i-banki",
      about: "ОТП Банк — надежный европейский банк в России. Выгодные дебетовые карты, кэшбэк рублями и высокий процент на остаток.",
      conditions: "Оформление заявки онлайн с бесплатной доставкой представителем.",
      site: "https://my.saleads.pro/s/trhde?erid=2Vtzqw1xtQh",
      activeBloggers: 4900,
    },
    affiliate: {
      link: "https://my.saleads.pro/s/trhde?erid=2Vtzqw1xtQh",
      landingLink: "https://my.saleads.pro/s/trhde?erid=2Vtzqw1xtQh",
      ordMarker: "2Vtzqw1xtQh",
      ordText: "Реклама. erid: 2Vtzqw1xtQh",
    },
    extraLinks: [],
  },
];