import type { Coupon } from "@/lib/types";

const A = (link: string) => ({
  link,
  landingLink: link,
  ordMarker: "",
  ordText: "",
});

export const DEV_MOCK_COUPONS: Coupon[] = [
  {
    id: 1001,
    promocode: {
      id: 1001,
      code: "YA25",
      bonusName: "Скидка 25%",
      terms:
        "Скидка 25% на весь ассортимент косметики и парфюмерии при заказе от 2 000 ₽.",
      expires: "2026-09-30",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: false,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 101,
      name: "Золотое Яблоко",
      slug: "zolotoe-yabloko",
      logo: null,
      category: "Красота",
      categorySlug: "krasota",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/zolotoe-yabloko",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/zolotoe-yabloko?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1002,
    promocode: {
      id: 1002,
      code: "LAMODA15",
      bonusName: "Скидка 15%",
      terms:
        "15% скидка на первый заказ одежды и обуви, включая распродажу.",
      expires: "2026-09-15",
      isHit: false,
      isUniversal: true,
      isFirstOrderOnly: true,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 102,
      name: "Lamoda",
      slug: "lamoda",
      logo: null,
      category: "Одежда",
      categorySlug: "odezhda",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/lamoda",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/lamoda?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1003,
    promocode: {
      id: 1003,
      code: "DNS10",
      bonusName: "Скидка 10%",
      terms:
        "10% на компьютеры, ноутбуки и комплектующие. Действует на всё кроме акционных позиций.",
      expires: "2026-10-31",
      isHit: false,
      isUniversal: false,
      isFirstOrderOnly: false,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 103,
      name: "DNS",
      slug: "dns",
      logo: null,
      category: "Электроника",
      categorySlug: "elektronika",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/dns",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/dns?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1004,
    promocode: {
      id: 1004,
      code: "SAMOKAT300",
      bonusName: "Скидка 300 ₽",
      terms:
        "Скидка 300 ₽ на первый заказ продуктов с доставкой от 1 500 ₽.",
      expires: "2026-08-31",
      isHit: false,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 104,
      name: "Самокат",
      slug: "samokat",
      logo: null,
      category: "Продукты",
      categorySlug: "produkty",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/samokat",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/samokat?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1005,
    promocode: {
      id: 1005,
      code: "LETUAL3",
      bonusName: "3=2",
      terms:
        "Три товара по цене двух на парфюмерию и декоративную косметику.",
      expires: "2026-09-30",
      isHit: true,
      isUniversal: false,
      isFirstOrderOnly: false,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 105,
      name: "Летуаль",
      slug: "letual",
      logo: null,
      category: "Красота",
      categorySlug: "krasota",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/letual",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/letual?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1006,
    promocode: {
      id: 1006,
      code: "SPORT20",
      bonusName: "Скидка 20%",
      terms:
        "20% скидка на спортивную одежду, обувь и инвентарь для тренировок.",
      expires: "2026-09-30",
      isHit: false,
      isUniversal: false,
      isFirstOrderOnly: false,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 106,
      name: "Спортмастер",
      slug: "sportmaster",
      logo: null,
      category: "Одежда",
      categorySlug: "odezhda",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/sportmaster",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/sportmaster?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1007,
    promocode: {
      id: 1007,
      code: "MVIDEO15",
      bonusName: "Кэшбэк 15%",
      terms:
        "Кэшбэк 15% бонусами на телевизоры, смартфоны и бытовую технику.",
      expires: "2026-10-15",
      isHit: false,
      isUniversal: false,
      isFirstOrderOnly: false,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 107,
      name: "М.Видео",
      slug: "m-video",
      logo: null,
      category: "Электроника",
      categorySlug: "elektronika",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/m-video",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/m-video?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1008,
    promocode: {
      id: 1008,
      code: "VKUSVILL15",
      bonusName: "Скидка 15%",
      terms:
        "15% на первый заказ в приложении. Промокод суммируется со скидками недели.",
      expires: "2026-09-20",
      isHit: false,
      isUniversal: true,
      isFirstOrderOnly: true,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 108,
      name: "ВкусВилл",
      slug: "vkusvill",
      logo: null,
      category: "Продукты",
      categorySlug: "produkty",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/vkusvill",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/vkusvill?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1009,
    promocode: {
      id: 1009,
      code: "OSTIN30",
      bonusName: "Скидка 30%",
      terms:
        "30% скидка на одежду для всей семьи при заказе на сайте магазина.",
      expires: "2026-09-10",
      isHit: false,
      isUniversal: false,
      isFirstOrderOnly: false,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 109,
      name: "O'STIN",
      slug: "ostin",
      logo: null,
      category: "Одежда",
      categorySlug: "odezhda",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/ostin",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/ostin?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1010,
    promocode: {
      id: 1010,
      code: "HOFF20",
      bonusName: "Скидка 20%",
      terms:
        "20% на мебель и товары для дома из каталога. Действует на первую покупку.",
      expires: "2026-10-31",
      isHit: false,
      isUniversal: false,
      isFirstOrderOnly: true,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 110,
      name: "Hoff",
      slug: "hoff",
      logo: null,
      category: "Дом",
      categorySlug: "dom",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/hoff",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/hoff?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1011,
    promocode: {
      id: 1011,
      code: "S7FLY",
      bonusName: "Скидка 15%",
      terms:
        "15% на авиабилеты по России и СНГ при оплате на сайте авиакомпании.",
      expires: "2026-11-30",
      isHit: false,
      isUniversal: false,
      isFirstOrderOnly: false,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 111,
      name: "S7 Airlines",
      slug: "s7",
      logo: null,
      category: "Путешествия",
      categorySlug: "puteshestviya",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/s7",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/s7?subid=promofact"),
    extraLinks: [],
  },
  {
    id: 1012,
    promocode: {
      id: 1012,
      code: "YM500",
      bonusName: "Скидка 500 ₽",
      terms:
        "500 ₽ на первый заказ от 3 000 ₽. Подходит для электроники и бытовой техники.",
      expires: "2026-09-25",
      isHit: false,
      isUniversal: true,
      isFirstOrderOnly: true,
      region: null,
      isBarcode: false,
      barcodeImage: null,
      group: null,
    },
    store: {
      id: 112,
      name: "Яндекс Маркет",
      slug: "yandex-market",
      logo: null,
      category: "Электроника",
      categorySlug: "elektronika",
      about: null,
      conditions: null,
      site: "https://perfluence.net/campaign/yandex-market",
      activeBloggers: 0,
    },
    affiliate: A("https://perfluence.net/campaign/yandex-market?subid=promofact"),
    extraLinks: [],
  },
];


export const DEV_MOCK_RESULTS = [
  {
    datetime: "2026-06-21 23:59:59",
    fee: 91,
    stackedCount: 1,
    promocode: "FW494632",
    comment: "Скидка 100% на сервисный сбор на первую и все повторные покупки билетов от 3 000 ₽",
    project: { id: 1965, name: "Яндекс Афиша", logo: "https://s3sc.perfluence.net/logos/16748253656362.png" },
  },
  {
    datetime: "2026-06-20 23:59:59",
    fee: 78,
    stackedCount: 1,
    promocode: "F95709",
    comment: "Скидка 750 ₽ на первую покупку билетов от 5 000 ₽",
    project: { id: 1965, name: "Яндекс Афиша", logo: "https://s3sc.perfluence.net/logos/16748253656362.png" },
  },
  {
    datetime: "2026-06-20 23:59:59",
    fee: 130,
    stackedCount: 1,
    promocode: "FW494632",
    comment: "Скидка 100% на сервисный сбор на первую и все повторные покупки билетов от 3 000 ₽",
    project: { id: 1965, name: "Яндекс Афиша", logo: "https://s3sc.perfluence.net/logos/16748253656362.png" },
  },
  {
    datetime: "2026-06-19 23:59:59",
    fee: 98.8,
    stackedCount: 1,
    promocode: "FW494632",
    comment: "Скидка 100% на сервисный сбор на первую и все повторные покупки билетов от 3 000 ₽",
    project: { id: 1965, name: "Яндекс Афиша", logo: "https://s3sc.perfluence.net/logos/16748253656362.png" },
  },
  {
    datetime: "2026-06-19 23:59:59",
    fee: 156,
    stackedCount: 1,
    promocode: "FW494632",
    comment: "Скидка 100% на сервисный сбор на первую и все повторные покупки билетов от 3 000 ₽",
    project: { id: 1965, name: "Яндекс Афиша", logo: "https://s3sc.perfluence.net/logos/16748253656362.png" },
  },
  {
    datetime: "2026-06-18 23:59:59",
    fee: 68.9,
    stackedCount: 1,
    promocode: "FW494632",
    comment: "Скидка 100% на сервисный сбор на первую и все повторные покупки билетов от 3 000 ₽",
    project: { id: 1965, name: "Яндекс Афиша", logo: "https://s3sc.perfluence.net/logos/16748253656362.png" },
  },
];
